demographic_data: false
dropout_prob: 0
hidden_dims:
- 128
- 64
- 32
input_dim: 38
learning_rate: 0.0001
loss_type: rmse
lr_scheduler: true
output_dim: 7
predict_fam_lik: false
target_name: brand_identity
use_batch_norm: false
weight_decay: true
